import { Button, Flex, Text, useBreakpointValue } from "@chakra-ui/react";
import GoldenScene from "../components/three/Golden/GoldenScene";
import styles from "../styles/Home.module.css";
import { motion, useScroll, useTransform } from "framer-motion";
import AtomScene from "../components/Atom/AtomScene";
import AboutMe from "../components/about/AboutMe";
import { useInView } from "react-intersection-observer";
import WhyMe from "../components/why/WhyMe";

const test = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

export default function Home() {
  const breakPointSizes = useBreakpointValue({
    sm: "20px",
    md: "45px",
    lg: "72px",
  });

  return (
    <div className={styles.anim_gradient}>
      <Flex
        w="100%"
        maxW="100vw"
        h="1000vh"
        direction="column"
        overflowX="hidden"
      >
        <Flex h="100vh" w="100%">
          <GoldenScene />
        </Flex>
        <Flex w="100%" justify="space-between" align="center">
          <Flex>
            <AboutMe />
          </Flex>
          <Flex w="500px" h="500px" justify="center" align="center">
            <AtomScene />
          </Flex>
        </Flex>
        {/* <Flex h="100%" direction="column">
          <Flex w="100%">
            <Flex w="100%" h="100vh" justify="center" align="top">
              <Caixa speed={13} />
            </Flex>
            <Flex w="100%" h="100vh" justify="center" align="center">
              <Caixa speed={-4} />
            </Flex>
          </Flex>
          <Flex w="100%">
            <Flex w="100%" h="100vh" justify="center" align="top">
              <Caixa speed={10} />
            </Flex>
            <Flex w="100%" h="100vh" justify="center" align="center">
              <Caixa speed={-4} />
            </Flex>
          </Flex>
          <Flex w="100%">
            <Flex w="100%" h="100vh" justify="center" align="top">
              <Caixa speed={7} />
            </Flex>
            <Flex w="100%" h="100vh" justify="center" align="center">
              <Caixa speed={-4} />
            </Flex>
          </Flex>
        </Flex> */}
        <WhyMe />
      </Flex>
    </div>
  );
}

{
  /* <Head>
  <title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head> */
}

function Caixa({ speed }) {
  const { scrollYProgress } = useScroll();
  const { ref, inView } = useInView({ threshold: 0.4 });
  // console.log(current);
  const yValue = useTransform(scrollYProgress, [0.1, 0.5], [0, 100 * speed]);
  return (
    <Flex
      ref={ref}
      as={motion.div}
      style={{ y: inView ? yValue : null }}
      h="300px"
      w="300px"
      bg="brown"
    />
  );
}
