import { Button, Flex, Text, useBreakpointValue } from "@chakra-ui/react";
import { Canvas, useFrame } from "@react-three/fiber";
import * as THREE from "three";
import Square from "../components/three/Square";

import {
  Environment,
  Html,
  OrbitControls,
  Sky,
  Stars,
} from "@react-three/drei";
import AnimatedSphere from "../components/three/AnimatedSphere";
import { Suspense, useRef } from "react";
import WavyText from "../components/WavyText";
import Controls from "../components/three/Controls";
import PendularScene from "../components/three/PendularScene";
import ReactScene from "../components/three/ReactScene";
import CloudWordsScene from "../components/three/CloudWordsScene";

const test = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

export default function Home() {
  const breakPointSizes = useBreakpointValue({
    sm: "20px",
    md: "45px",
    lg: "72px",
  });

  return (
    <Flex
      w="100%"
      maxW="100vw"
      h="3000px"
      bg="lightgoldenrodyellow"
      direction="column"
      overflowX="hidden"
    >
      <Flex justify="center" align="center" w="100%" h="100vh">
        <PendularScene />
      </Flex>
      <Flex w="100%" h="100%" bg="purple.800" justify="space-between">
        <Flex direction="column" gap="15px">
          <Text>ahsdoiahsiodhaoidhoad</Text>
          <Text>ahsdoiahsiodhaoidhoad</Text>
          <Text>ahsdoiahsiodhaoidhoad</Text>
        </Flex>

        <Flex h="300px" w="300px" justify="center" align="center">
          <ReactScene />
        </Flex>
        <Flex h="300px" w="300px" justify="center" align="center">
          <Suspense fallback={null}>
            <CloudWordsScene />
          </Suspense>
        </Flex>
      </Flex>
    </Flex>
  );
}

{
  /* <Head>
  <title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head> */
}
