import { Button, Flex, Text, useBreakpointValue } from "@chakra-ui/react";
import { Canvas } from "@react-three/fiber";
import * as THREE from "three";
import Square from "../components/three/Square";

import { Html, OrbitControls, Stars } from "@react-three/drei";
import AnimatedSphere from "../components/three/AnimatedSphere";
import { Suspense } from "react";
import WavyText from "../components/WavyText";

const test = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

export default function Home() {
  const breakPointSizes = useBreakpointValue({
    sm: "20px",
    md: "45px",
    lg: "72px",
  });
  return (
    <Flex
      w="100%"
      maxW="100vw"
      h="3000px"
      bg="lightgoldenrodyellow"
      direction="column"
      overflowX="hidden"
    >
      <Flex
        justify="center"
        align="center"
        bg="black"
        w="100%"
        h="100vh"
        onMouseDown={() => {
          return false;
        }}
      >
        <Canvas
          style={{
            width: "100%",
            height: "100%",
          }}
          camera={{ position: [0, 5, 10] }}
        >
          <Stars />
          <Html fullscreen>
            <Flex
              h="100%"
              justify="center"
              align="center"
              mt="105px"
              direction="column"
              gap="15px"
            >
              <WavyText
                size={breakPointSizes}
                text="Welcome"
                delayDuration={1}
              />
              <WavyText
                size={breakPointSizes}
                text="I'm Yago"
                delayDuration={1.8}
              />
              <WavyText
                size={breakPointSizes}
                text="Frontend Developer"
                delayDuration={2.6}
              />
            </Flex>
          </Html>
          <OrbitControls enableZoom={false} />
          <ambientLight intensity={0.5} />
          <directionalLight position={[-2, 5, 1]} intensity={1} />
          {test.map((number, index) => {
            return (
              <Square
                vector={new THREE.Vector3(0, -1 - index, -number * 4.2)}
                frequency={1.2 + number * 0.05}
                number={number}
              />
            );
          })}
          {/* <Square /> */}
        </Canvas>
      </Flex>
      {/* <Flex
        h="100%"
        justify="center"
        align="center"
        mt="105px"
        direction="column"
        gap="15px"
      >
        <WavyText text="Welcome" delayDuration={1} />
        <WavyText text="I'm Yago" delayDuration={1.8} />
        <WavyText text="Frontend Developer" delayDuration={2.6} />
      </Flex> */}
    </Flex>
  );
}

{
  /* <Head>
  <title>Create Next App</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
</Head> */
}
